### PR TITLE
Adds a few more bits and bobs harvested from projects.

### PR DESCRIPTION
**Pull request by DaRosenberg**

### CODE REVIEW

**Review by sfmskywalker — APPROVED** [review]
Looks very good. The only feature I'm unfamiliar with is the `PartialAlias` thing. What is it for?

**Comment by DaRosenberg** [comment]
@sfmskywalker It's a type of route that matches on the alias being only part of the URL, so that you can append a further subpath to the request URL that might be used by client-side routing, and Orchard will still route to the content item even though the path is not an exact match.

**Comment by sfmskywalker** [comment]
Right, I remember now. You used it in combination with Angular apps.

**Comment by DaRosenberg** [comment]
Yep, exactly.

**Pull request merged**
